# Generated by Django 4.2.7 on 2025-12-13 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('image_size', models.IntegerField(help_text='Size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('processing_duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='tasks_proce_created_1a3b7d_idx'), models.Index(fields=['status'], name='tasks_proce_status_973685_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtractedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('position_index', models.IntegerField(default=0, help_text='Order of appearance in the original image')),
                ('confidence_score', models.FloatField(blank=True, help_text='OCR confidence for this task', null=True)),
                ('bbox_x', models.IntegerField(blank=True, null=True)),
                ('bbox_y', models.IntegerField(blank=True, null=True)),
                ('bbox_width', models.IntegerField(blank=True, null=True)),
                ('bbox_height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_tasks', to='tasks.processingjob')),
            ],
            options={
                'ordering': ['job', 'position_index'],
                'indexes': [models.Index(fields=['job', 'position_index'], name='tasks_extra_job_id_70f596_idx')],
            },
        ),
    ]
